name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: myregistry.example.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push images
        run: |
          for service in pricing-service forecasting-service ancillary-service offer-service pss-integration-service pros-integration-service; do
            cd services/$service
            docker build -t myregistry.example.com/airline-fare-optimization:$service-latest .
            docker push myregistry.example.com/airline-fare-optimization:$service-latest
            cd ../../..
          done

      - name: Deploy to Kubernetes
        run: |
          chmod +x ci-cd/k8s-deploy.sh
          ./ci-cd/k8s-deploy.sh
