# config.yaml - Ancillary Service Configuration
bundling:
  family_bundle_discount: 0.15
  business_bundle_discount: 0.10
  standard_bundle_discount: 0.05
thresholds:
  max_bundle_items: 3
  min_total_price_for_discount: 20
external:
  ancillary_api_url: "http://ancillary.api.example.com"
# These values are based on market research as detailed in docs/product/Ancillary_Services_PRD.md.
