global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dfae_services'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: prod
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: (pricing-service|forecasting-service|portal|ancillary-service|offer-service)
