# config.yaml
# Configuration for User Management Service

auth:
  jwt_secret: "YOUR_SECRET_KEY_HERE"
  token_expiry_seconds: 3600  # Token valid for 1 hour

password_policy:
  min_length: 8
  require_numbers: true
  require_special: true

api:
  port: 5003
  base_path: "/api/user"

logging:
  level: "INFO"
