# azure-pipelines.yml
# Azure Pipelines definition for building, testing, and deploying the project.

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  registry: 'myregistry.example.com'
  imageTag: 'latest'

stages:
- stage: BuildTest
  jobs:
  - job: BuildAndTest
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    - script: |
        for service in pricing-service forecasting-service ancillary-service offer-service pss-integration-service pros-integration-service; do
          cd services/$service
          pip install -r requirements.txt
          pytest --maxfail=1 --disable-warnings -q
          cd ../../..
        done
      displayName: 'Build and Test all Services'
- stage: Deploy
  jobs:
  - job: DeployToK8s
    steps:
    - checkout: self
    - script: |
        for service in pricing-service forecasting-service ancillary-service offer-service pss-integration-service pros-integration-service; do
          cd services/$service
          docker build -t $(registry)/dynamic-fare-adjustment-engine:$service-$(imageTag) .
          docker push $(registry)/dynamic-fare-adjustment-engine:$service-$(imageTag)
          cd ../../..
        done
      displayName: 'Build and Push Docker Images'
    - script: |
        chmod +x ci-cd/k8s-deploy.sh
        ./ci-cd/k8s-deploy.sh
      displayName: 'Deploy to Kubernetes'
